package com.wallnit.wallnitlogin;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;

public class WallnitTerms_of_Service extends AppCompatActivity {

    TextView t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21,t22,t23,t24;
    TextView t25,t26,t27,t28,t29,t30,t31,t32,t33,t34,t35,t36,t37,t38,t39,t40,t41,t42,t43,t44,t45,t46;
    TextView t47,t48,t49,t50,t51,t52,t53,t54,t55,t56,t57,t58,t59,t60,t61,t62,t63,t64,t65,t66,t67,t68;
    TextView t69,t70,t71,t72,t73,t74,t75,t76,t77,t78,t79,t80,t81,t82,t83,t84,t85,t86,t87,t88,t89,t90,t91,t92;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_wallnit_terms_of__service);
        t1=(TextView) findViewById(R.id.agreement_first);
        t2=(TextView) findViewById(R.id.agreement_second);
        t3=(TextView) findViewById(R.id.grant_agreement_first);
        t4=(TextView) findViewById(R.id.grant_agreement_second);
        t5=(TextView) findViewById(R.id.first_of_first);
        t6=(TextView) findViewById(R.id.first_of_second);
        t7=(TextView) findViewById(R.id.first_of_third);
        t8=(TextView) findViewById(R.id.first_of_fourth);
        t9=(TextView) findViewById(R.id.first_of_fifth);
        t10=(TextView) findViewById(R.id.first_of_sixth);
        t11=(TextView) findViewById(R.id.first_of_seventh);
        t12=(TextView) findViewById(R.id.first_of_eighth);
        t13=(TextView) findViewById(R.id.first_of_ninth);
        t14=(TextView) findViewById(R.id.first_of_tenth);
        t15=(TextView) findViewById(R.id.first_of_eleventh);
        t16=(TextView) findViewById(R.id.first_of_twelth);
        t17=(TextView) findViewById(R.id.first_of_thirteen);
        t18=(TextView) findViewById(R.id.first_of_fourteen);
        t19=(TextView) findViewById(R.id.first_of_fifteen);
        t20=(TextView) findViewById(R.id.termination_or_suspensionacc);
        t21=(TextView) findViewById(R.id.termination_first);
        t22=(TextView) findViewById(R.id.termination_second);
        t23=(TextView) findViewById(R.id.reservation_of_right);
        t24=(TextView) findViewById(R.id.reservation_first);
        t25=(TextView) findViewById(R.id.reservation_first_of_first);
        t26=(TextView) findViewById(R.id.reservation_first_of_second);
        t27=(TextView) findViewById(R.id.reservation_first_of_third);
        t28=(TextView) findViewById(R.id.reservation_first_of_fourth);
        t29=(TextView) findViewById(R.id.duty_of_user);
        t30=(TextView) findViewById(R.id.duty_first);
        t31=(TextView) findViewById(R.id.duty_first_of_first);
        t32=(TextView) findViewById(R.id.duty_first_of_second);
        t33=(TextView) findViewById(R.id.duty_first_of_third);
        t34=(TextView) findViewById(R.id.duty_first_of_fourth);
        t35=(TextView) findViewById(R.id.duty_first_of_fifth);
        t36=(TextView) findViewById(R.id.duty_first_of_sixth);
        t37=(TextView) findViewById(R.id.duty_first_of_seventh);
        t38=(TextView) findViewById(R.id.duty_second);
        t39=(TextView) findViewById(R.id.duty_third);
        t40=(TextView) findViewById(R.id.copyright);
        t41=(TextView) findViewById(R.id.copyright_first);
        t42=(TextView) findViewById(R.id.copyright_second);
        t43=(TextView) findViewById(R.id.copyright_third);
        t44=(TextView) findViewById(R.id.copyright_fourth);
        t45=(TextView) findViewById(R.id.copyright_fifth);
        t46=(TextView) findViewById(R.id.intellectual);
        t47=(TextView) findViewById(R.id.intellectual_first);
        t48=(TextView) findViewById(R.id.privacy);
        t49=(TextView) findViewById(R.id.privacy_first);
        t50=(TextView) findViewById(R.id.third_party_links);
        t51=(TextView) findViewById(R.id.thirdparty_first);
        t52=(TextView) findViewById(R.id.thirdparty_second);
        t53=(TextView) findViewById(R.id.addition_alteration);
        t54=(TextView) findViewById(R.id.addition_alteration_first);
        t55=(TextView) findViewById(R.id.addition_alteration_second);
        t56=(TextView) findViewById(R.id.indemnification);
        t57=(TextView) findViewById(R.id.indemnification_first);
        t58=(TextView) findViewById(R.id.laws_applicable);
        t59=(TextView) findViewById(R.id.laws_applicable_first);
        t60=(TextView) findViewById(R.id.jurisdiction);
        t61=(TextView) findViewById(R.id.jurisdiction_first);
        t62=(TextView) findViewById(R.id.note);
        t63=(TextView) findViewById(R.id.note_desc);
        t64=(TextView) findViewById(R.id.waiver);
        t65=(TextView) findViewById(R.id.waiver_first);
        t66=(TextView) findViewById(R.id.severability);
        t67=(TextView) findViewById(R.id.severability_first);
        t68=(TextView) findViewById(R.id.superseding);
        t69=(TextView) findViewById(R.id.superseding_first);
        t70=(TextView) findViewById(R.id.notice);
        t71=(TextView) findViewById(R.id.notice_first);
        t72=(TextView) findViewById(R.id.notice_second);
        t73=(TextView) findViewById(R.id.notice_third);
        t74=(TextView) findViewById(R.id.unforeseen);
        t75=(TextView) findViewById(R.id.unforeseen_first);
        t76=(TextView) findViewById(R.id.unforeseen_second);
        t77=(TextView) findViewById(R.id.limitation);
        t78=(TextView) findViewById(R.id.limitation_first);
        t79=(TextView) findViewById(R.id.contact_us);
        t80=(TextView) findViewById(R.id.contact_us_first);
        t81=(TextView) findViewById(R.id.grievance_officer);
        t82=(TextView) findViewById(R.id.grievance_officer_first);
        t83=(TextView) findViewById(R.id.grievance_officer_nameattr);
        t84=(TextView) findViewById(R.id.grievance_officer_name);
        t85=(TextView) findViewById(R.id.grievance_officer_addreattr);
        t86=(TextView) findViewById(R.id.grievance_officer_addre);
        t87=(TextView) findViewById(R.id.grievance_officer_phoneattr);
        t88=(TextView) findViewById(R.id.grievance_officer_phone);
        t89=(TextView) findViewById(R.id.grievance_officer_mailattr);
        t90=(TextView) findViewById(R.id.grievance_officer_mail);
        t91=(TextView) findViewById(R.id.grievance_officer_timingattr);
        t92=(TextView) findViewById(R.id.grievance_officer_timing);
        t1.setText("Hello! Thank You for using Wallnit. We appreciate that you took some time to read the terms of services of Wallnit.");
        t2.setText("This agreement is between Wallnit (hereinafter referred as 'We' or 'Us' or 'Our') and User (hereinafter referred as 'You'). It contains all details and information about how you are suppose to use this website. LOGGING-IN CONFIRMS THAT YOU AGREE WITH OUR TERMS OF SERVICES PRIVACY POLICY AND AGREE TO CREATE A LEGAL AGREEMENT WITH US. You also agree to be bound by our Privacy Policy. Kindly read the terms of services and Privacy policy carefully before logging-in.");
        t3.setText("We hereby grant you the right to use our services for free anywhere in the World.");
        t4.setText("The rights includes right to browse; read news; post link & quotes; comment; share; debate; blogging; upload photos, graphics, create circles and other such services as provided. The rights as mentioned are subjected to following conditions.");
        t5.setText("You shall be above 12 years of age to use the services;");
        t6.setText("You shall furnish all the information correct while registering and will keep your information up-to-date;");
        t7.setText("You shall use our services for personal use only and not for commercial purpose;");
        t8.setText("You shall not post or send any information that is grossly offensive or has menacing character;");
        t9.setText("You shall not post or send anything or indulge in any activity on the website that may harm the website, or its security, or its business or its goodwill;");
        t10.setText("You shall not post or send any information that you know or believe to be false, for the purpose of causing annoyance, disturbance, inconvenience, danger, insult, obstruction, injury, criminal intimidation, enmity, hatred or ill-will;");
        t11.setText("You shall not post or share any indecent, immoral, blasphemous, defamatory, false or misleading contents on the website;");
        t12.setText("You shall not indulge in any activities like spamming, chain letters, pyramid schemes, viruses, unsolicited emails or any other technologies that may harm us, or the interests or property of other users;");
        t13.setText("You shall not violate the rights of other users to access their account or interfering into their account without their consent or indulge in any activity that will lead to violation of the privacy of any other user or third party;");
        t14.setText("You shall not indulge in any dishonest or fraudulent activity of using the password or other unique identification of other users or any other person;");
        t15.setText("You shall not publish or transmit any obscene material or any material which contains sexually explicit act or conduct;");
        t16.setText("You shall not host, display, upload, modify, publish, transmit, update or share any information that infringes any patent, trademark, copyright or other proprietary rights;");
        t17.setText("You shall not host, display, upload, modify, publish, transmit, update or share any information that Contains software viruses or any other computer code, files or programs designed to interrupt, design or limit the functionality of any computer resources;");
        t18.setText("You shall not host, display, upload, modify, publish, transmit, update or share any information that threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence of is insulting any other nation;");
        t19.setText("You shall not violate any applicable laws of India or any International law.");
        t20.setText("2. Termination or suspension of Account");
        t21.setText("We have the capacity and right to terminate or suspend your account if we found or have reason to believe that you have violated any rule, as mentioned under 1.2, without giving any clarification or notice regarding the termination of your account.");
        t22.setText("You will solely responsible for yours acts and we cannot be held liable for any loss to you or any third party.");
        t23.setText("3. Reservation of Rights");
        t24.setText("We reserve some of the rights that have been granted to you, even if the exercise of the rights proves detrimental to your rights.");
        t25.setText("The right to discontinue your account or services;");
        t26.setText("Restrict your from accessing any content(s) of the website;");
        t27.setText("The right to add, change or remove any content(s) or information(s) of the website;");
        t28.setText("Your feedbacks, comments, suggestions, regarding the website are entirely voluntary for us to follow or reply. We shall not bind by your suggestions or replies.");
        t29.setText("4. Duty of User");
        t30.setText("You have certain duty regarding your account to keep it safe, so as to prevent it from misuse by third party.");
        t31.setText("You shall use your account for your personal use and will not share or delegate your password with anyone.");
        t32.setText("You shall log out your account whenever you are not having access to it.");
        t33.setText("You must change your password frequently, so that other person cannot have access to it.");
        t34.setText("You shall manage your privacy settings in such a way that only particulars users whom you intent to show can see your information or your post(s).");
        t35.setText("You shall abide-by the Terms of Services and Privacy policy.");
        t36.setText("You shall notify us, if there is any breach or misuse of account or password, as soon as possible, so that we can take precautions to keep it safe.");
        t37.setText("In case you change or deactivate your mobile number you will update the information as soon as possible so that other person who acquires your mobile number does not misuse your account.");
        t38.setText("We will not be liable for any loss or damage arises due to your failure.");
        t39.setText("You shall be responsible for maintaining confidentiality of the display name and password and other activities that occur under your account.");
        t40.setText("5. Copyright");
        t41.setText("All the content you post or share on the website belong and owned by you and does not violate any other person right or these terms or any law for time being force in India.");
        t42.setText("You agree and grant us nonÂ¬exclusive, royaltyÂ¬ free, transferable, sub licensable, worldwide license to use, host, store, display, reproduce, repost, communicate, publish, modify, create derivative works, perform, and distribute any content(s) or information(s) that you posts.");
        t43.setText("We do not claim any right or ownership over the contents that you post or share.");
        t44.setText("If you want to notify us regarding infringement of your copyright, then you write us at infreport@wallnit.com. We would remove any of the content if we believe that it has violated someone else's copyright.");
        t45.setText("We shall not be liable for infringement of your copyright or trademark.");
        t46.setText("6. Intellectual Property");
        t47.setText("All the rights are reserved under the Copyright Act. You cannot reproduce or use the word 'WALLNIT' without the approval of the concerned authority. Any misuse or reproduction may bring penal action under the laws laid by the government of India.");
        t48.setText("7. Privacy");
        t49.setText("In order to see how we gather, use and share the information that you provide kindly review the Privacy policy. Logging-in confirms that you consent to the gathering, use, and sharing of the information that you provide to Wallnit and its affiliates.");
        t50.setText("8. Third Party Links");
        t51.setText("The website contains third party links which are not controlled or marketed by us and we will not be liable for any loss that you suffer due to access of the third party links.");
        t52.setText("It is for you to make investigation before proceeding to these links. You will be governed by the terms of the third party links. We do not have any role or cannot be held liable for any loss which you suffer.");
        t53.setText("9. Addition or Alteration of terms");
        t54.setText("The present terms are subjected to certain addition or alteration. Weâ€™ll inform you about the addition or modification in the terms through our services (by posting a notification on your wall). The new terms will supersede the old terms in the agreement.");
        t55.setText("If you do not wish to abide by the new terms, you can discontinue the use of services immediately from the date of communication of the addition or alteration of terms, otherwise it would be deemed to have been accepted.");
        t56.setText("10. Indemnification");
        t57.setText("You shall indemnify us, or ours associates, agents, employees, subsidies, licensee or any other persons related to the company from and against any or all claims, demands, actions, causes of action, suits, proceedings, losses, damages, costs, and expenses, including attorney's fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms, Privacy Policy, any other policy followed by the Company and / or violation of any applicable law or the rights (including infringement of intellectual property rights) of a third party.");
        t58.setText("11. Laws applicable");
        t59.setText("Terms of services and privacy policy shall be governed by and interpreted in accordance with the laws of India.");
        t60.setText("12. Jurisdiction");
        t61.setText("If any dispute arises in connection with the website, terms of services, privacy policy or any other matter related with the website it shall have an exclusive jurisdiction of the competent court at Jaipur, Rajasthan.");
        t62.setText("Note - ");
        t63.setText("We encourage you to first contact us regarding any dispute related with the website so that it can be amicably settled.");
        t64.setText("13. Waiver");
        t65.setText("Failure to enforce any of the rights in these terms, in case of default, will not constitute waiver of such right, unless specified in writing by us.");
        t66.setText("14. Severability");
        t67.setText("If any provision(s) or the part of the provision(s) is inconsistent with the laws or statute of Indian law or is held to be inconsistent or unenforceable by the court of competent jurisdiction, then that provision(s) or part of the provision(s) will be held to be unenforceable, but such inconsistency will have no effect on the validity of the other provision(s) of these terms.");
        t68.setText("15. Superseding of this Agreement");
        t69.setText("This agreement supersedes all the previous agreement, negotiations whether oral or written between you and us regarding the subject matter contained herein.");
        t70.setText("16. Notice");
        t71.setText("We may give notice to you by the means of electronic mail to your email address or in writing to your address as mentioned in your account.");
        t72.setText("You may send letter or mail to us at anytime by sending a mail or e-mail to the following address:");
        t73.setText("Mailing Address: 1, Satya Vihar Colony, Behind Cafe 99, Lal Kothi, Jaipur, Rajasthan:\n" +
                "Email Address: helpdesk@wallnit.com");
        t74.setText("17. Unforeseen Circumstances");
        t75.setText("Access to the Website may be interrupted due to routine maintenance and for the introduction of new features. We shall not be responsible for any delays, delivery failures, and interruptions due to routine maintenance and for the introduction of any new features, or other damage resulting from such problems.");
        t76.setText("We shall not be in default for failing to perform any obligation hereunder if such failure is caused solely by supervening conditions beyond its respective control, including without limitation acts of God, civil commotion, riots, crowd disorder, strikes, lock-outs, other industrial actions, actual or threatened terrorist activities, war, fire, technical or power failure, failure of third party networking equipment, failure of the public Internet, interruptions, disruptions or malfunctions, explosions, storm, flood, earthquake, subsidence, epidemic or other natural or physical disaster, labour disputes or governmental demands or restrictions");
        t77.setText("18. Limitation of Liability");
        t78.setText("WALLNIT, ITS EMPLOYEE, PARTNERS SHALL NOT BE LIABLE TO YOU OR ANY THIRD PERSON FOR ANY SPECIAL, INCIDENTIAL, INDIRECT, PUNUTIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND WITH REGARD TO THESE TERMS, EVEN IF YOU HAVE BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGE. NOR WILL BE LIABLE FOR ANY CONDUCT WHATSOEVER OF YOU OR ANY THIRD PARTY AND ANY SUCH RISK OR DAMAGE RESTS SOLELELY AND ENTIRELY WITH YOU.");
        t79.setText("19. Contact Us");
        t80.setText("You may feel free to contact us with regard to any matter related to this Website, we would be please to answer your questions or suggestions.");
        t81.setText("20. GRIEVANCE OFFICER");
        t82.setText("In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:");
        t83.setText("Name : ");
        t84.setText("Gaurav Kumawat");
        t85.setText("Office address : ");
        t86.setText("1, Satya Vihar Colony, Behind Cafe 99, Lal Kothi, Jaipur, Rajasthan");
        t87.setText("Phone : ");
        t88.setText("+91 9570664853");
        t89.setText("Mail : ");
        t90.setText("legalsupport@wallnit.com");
        t91.setText("Timing : ");
        t92.setText("10:00 AM to 6:00 PM (Monday to Saturday)");

    }
}
